# Generated by Django 3.0.4 on 2020-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='figure_cards',
            field=models.ManyToManyField(related_name='decks', to='flashcards.FigureCard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='text_cards',
            field=models.ManyToManyField(related_name='decks', to='flashcards.TextCard'),
        ),
    ]
