# Generated by Django 3.0.4 on 2020-03-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20200313_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='figure_cards',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='text_cards',
        ),
        migrations.AddField(
            model_name='figurecard',
            name='decks',
            field=models.ManyToManyField(related_name='figure_cards', to='flashcards.Deck'),
        ),
        migrations.AddField(
            model_name='textcard',
            name='decks',
            field=models.ManyToManyField(related_name='text_cards', to='flashcards.Deck'),
        ),
    ]
