# Generated by Django 3.0.4 on 2020-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20200315_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurecard',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='textcard',
            name='decks',
        ),
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(related_name='cards', to='flashcards.Deck'),
        ),
    ]
