# Generated by Django 3.0.4 on 2020-03-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20200315_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcard',
            name='card_ptr',
        ),
        migrations.DeleteModel(
            name='FigureCard',
        ),
        migrations.DeleteModel(
            name='TextCard',
        ),
    ]
