# Generated by Django 3.0.4 on 2020-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20200316_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='figure_raw',
            field=models.FileField(default='figure', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
