# Generated by Django 3.0.4 on 2020-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20200316_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='figure_raw',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
