# Generated by Django 3.0.4 on 2020-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_card_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='flashcards.Deck'),
        ),
    ]
