# Generated by Django 3.0.4 on 2020-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_auto_20200318_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(related_name='cards', to='flashcards.Deck'),
        ),
    ]
