# Generated by Django 3.0.4 on 2020-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_remove_card_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='figure_raw',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
