# Generated by Django 3.0.4 on 2020-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0018_auto_20200319_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='figure_raw',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
